/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window_gestion_reclam (void);
GtkWidget* create_window_afficher_reclam (void);
GtkWidget* create_dialog_echec_ajout_reclam (void);
GtkWidget* create_dialog_succes_ajout_reclam (void);
GtkWidget* create_dialog_echec_modif_reclam (void);
GtkWidget* create_dialog_succes_modif_reclam (void);
GtkWidget* create_window_dashboard_reclam (void);
