/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window_gestion_reclam (void)
{
  GtkWidget *window_gestion_reclam;
  GtkWidget *fixed1;
  GtkWidget *entry_id_reclam;
  GtkWidget *entry_cin_reclam;
  GtkWidget *entry_nom_reclam;
  GtkWidget *entry_prenom_reclam;
  GtkWidget *entryreclam;
  GtkObject *spinbutton_jour_reclam_adj;
  GtkWidget *spinbutton_jour_reclam;
  GtkObject *spinbutton_mois_reclam_adj;
  GtkWidget *spinbutton_mois_reclam;
  GtkObject *spinbutton_annee_reclam_adj;
  GtkWidget *spinbutton_annee_reclam;
  GtkWidget *eventbox1;
  GtkWidget *label1;
  GtkWidget *eventbox2;
  GtkWidget *label2;
  GtkWidget *eventbox3;
  GtkWidget *label3;
  GtkWidget *eventbox4;
  GtkWidget *label5;
  GtkWidget *eventbox5;
  GtkWidget *label6;
  GtkWidget *eventbox6;
  GtkWidget *combobox_reclam;
  GtkWidget *eventbox7;
  GtkWidget *label4;
  GtkWidget *eventbox8;
  GtkWidget *label10;
  GtkWidget *eventbox9;
  GtkWidget *label11;
  GtkWidget *eventbox10;
  GtkWidget *label12;
  GtkWidget *eventbox11;
  GtkWidget *label9;
  GtkWidget *eventbox12;
  GtkWidget *label7;
  GtkWidget *eventbox13;
  GtkWidget *label8;
  GtkWidget *eventbox14;
  GtkWidget *radiobutton_homme_reclam;
  GSList *radiobutton_homme_reclam_group = NULL;
  GtkWidget *eventbox15;
  GtkWidget *radiobutton_femme_reclam;
  GtkWidget *eventbox16;
  GtkWidget *checkbutton_prepa_reclam;
  GtkWidget *eventbox17;
  GtkWidget *checkbutton_ing_reclam;
  GtkWidget *eventbox18;
  GtkWidget *checkbutton_business_reclam;
  GtkWidget *eventbox19;
  GtkWidget *button_ajouter_reclam;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label13;
  GtkWidget *eventbox20;
  GtkWidget *button_modifier_reclam;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label14;
  GtkWidget *eventbox22;
  GtkWidget *button_afficher_reclam;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label15;
  GtkWidget *image10;

  window_gestion_reclam = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_gestion_reclam), _("Gestion de r\303\251clamation"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window_gestion_reclam), fixed1);

  entry_id_reclam = gtk_entry_new ();
  gtk_widget_show (entry_id_reclam);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_id_reclam, 216, 16);
  gtk_widget_set_size_request (entry_id_reclam, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id_reclam), 8226);

  entry_cin_reclam = gtk_entry_new ();
  gtk_widget_show (entry_cin_reclam);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_cin_reclam, 216, 56);
  gtk_widget_set_size_request (entry_cin_reclam, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_cin_reclam), 8226);

  entry_nom_reclam = gtk_entry_new ();
  gtk_widget_show (entry_nom_reclam);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_nom_reclam, 216, 104);
  gtk_widget_set_size_request (entry_nom_reclam, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nom_reclam), 8226);

  entry_prenom_reclam = gtk_entry_new ();
  gtk_widget_show (entry_prenom_reclam);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_prenom_reclam, 600, 104);
  gtk_widget_set_size_request (entry_prenom_reclam, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_prenom_reclam), 8226);

  entryreclam = gtk_entry_new ();
  gtk_widget_show (entryreclam);
  gtk_fixed_put (GTK_FIXED (fixed1), entryreclam, 216, 208);
  gtk_widget_set_size_request (entryreclam, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryreclam), 8226);

  spinbutton_jour_reclam_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton_jour_reclam = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_jour_reclam_adj), 1, 0);
  gtk_widget_show (spinbutton_jour_reclam);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton_jour_reclam, 200, 296);
  gtk_widget_set_size_request (spinbutton_jour_reclam, 60, 27);

  spinbutton_mois_reclam_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton_mois_reclam = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_mois_reclam_adj), 1, 0);
  gtk_widget_show (spinbutton_mois_reclam);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton_mois_reclam, 320, 296);
  gtk_widget_set_size_request (spinbutton_mois_reclam, 60, 27);

  spinbutton_annee_reclam_adj = gtk_adjustment_new (1, 2021, 2050, 1, 10, 10);
  spinbutton_annee_reclam = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_annee_reclam_adj), 1, 0);
  gtk_widget_show (spinbutton_annee_reclam);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton_annee_reclam, 440, 296);
  gtk_widget_set_size_request (spinbutton_annee_reclam, 60, 27);

  eventbox1 = gtk_event_box_new ();
  gtk_widget_show (eventbox1);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox1, 56, 16);
  gtk_widget_set_size_request (eventbox1, 64, 25);

  label1 = gtk_label_new (_("ID"));
  gtk_widget_show (label1);
  gtk_container_add (GTK_CONTAINER (eventbox1), label1);
  gtk_widget_set_size_request (label1, 64, 25);

  eventbox2 = gtk_event_box_new ();
  gtk_widget_show (eventbox2);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox2, 72, 64);
  gtk_widget_set_size_request (eventbox2, 64, 24);

  label2 = gtk_label_new (_("CIN"));
  gtk_widget_show (label2);
  gtk_container_add (GTK_CONTAINER (eventbox2), label2);
  gtk_widget_set_size_request (label2, 64, 24);

  eventbox3 = gtk_event_box_new ();
  gtk_widget_show (eventbox3);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox3, 48, 104);
  gtk_widget_set_size_request (eventbox3, 112, 25);

  label3 = gtk_label_new (_("Nom"));
  gtk_widget_show (label3);
  gtk_container_add (GTK_CONTAINER (eventbox3), label3);
  gtk_widget_set_size_request (label3, 112, 25);

  eventbox4 = gtk_event_box_new ();
  gtk_widget_show (eventbox4);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox4, 48, 168);
  gtk_widget_set_size_request (eventbox4, 104, 25);

  label5 = gtk_label_new (_("Service"));
  gtk_widget_show (label5);
  gtk_container_add (GTK_CONTAINER (eventbox4), label5);
  gtk_widget_set_size_request (label5, 104, 25);

  eventbox5 = gtk_event_box_new ();
  gtk_widget_show (eventbox5);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox5, 0, 216);
  gtk_widget_set_size_request (eventbox5, 192, 33);

  label6 = gtk_label_new (_("Votre r\303\251clamation"));
  gtk_widget_show (label6);
  gtk_container_add (GTK_CONTAINER (eventbox5), label6);
  gtk_widget_set_size_request (label6, 192, 33);

  eventbox6 = gtk_event_box_new ();
  gtk_widget_show (eventbox6);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox6, 224, 160);
  gtk_widget_set_size_request (eventbox6, 152, 31);

  combobox_reclam = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_reclam);
  gtk_container_add (GTK_CONTAINER (eventbox6), combobox_reclam);
  gtk_widget_set_size_request (combobox_reclam, 152, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_reclam), _("Service d'hebergement"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_reclam), _("Service de restauration"));

  eventbox7 = gtk_event_box_new ();
  gtk_widget_show (eventbox7);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox7, 448, 104);
  gtk_widget_set_size_request (eventbox7, 96, 25);

  label4 = gtk_label_new (_("Pr\303\251nom"));
  gtk_widget_show (label4);
  gtk_container_add (GTK_CONTAINER (eventbox7), label4);
  gtk_widget_set_size_request (label4, 96, 25);

  eventbox8 = gtk_event_box_new ();
  gtk_widget_show (eventbox8);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox8, 192, 264);
  gtk_widget_set_size_request (eventbox8, 49, 17);

  label10 = gtk_label_new (_("Jour"));
  gtk_widget_show (label10);
  gtk_container_add (GTK_CONTAINER (eventbox8), label10);
  gtk_widget_set_size_request (label10, 49, 17);

  eventbox9 = gtk_event_box_new ();
  gtk_widget_show (eventbox9);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox9, 312, 264);
  gtk_widget_set_size_request (eventbox9, 49, 17);

  label11 = gtk_label_new (_("Mois"));
  gtk_widget_show (label11);
  gtk_container_add (GTK_CONTAINER (eventbox9), label11);
  gtk_widget_set_size_request (label11, 49, 17);

  eventbox10 = gtk_event_box_new ();
  gtk_widget_show (eventbox10);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox10, 432, 264);
  gtk_widget_set_size_request (eventbox10, 56, 17);

  label12 = gtk_label_new (_("Ann\303\251e"));
  gtk_widget_show (label12);
  gtk_container_add (GTK_CONTAINER (eventbox10), label12);
  gtk_widget_set_size_request (label12, 56, 17);

  eventbox11 = gtk_event_box_new ();
  gtk_widget_show (eventbox11);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox11, 8, 304);
  gtk_widget_set_size_request (eventbox11, 160, 25);

  label9 = gtk_label_new (_("Date de r\303\251clamation"));
  gtk_widget_show (label9);
  gtk_container_add (GTK_CONTAINER (eventbox11), label9);
  gtk_widget_set_size_request (label9, 160, 25);

  eventbox12 = gtk_event_box_new ();
  gtk_widget_show (eventbox12);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox12, 48, 368);
  gtk_widget_set_size_request (eventbox12, 80, 25);

  label7 = gtk_label_new (_("Sexe"));
  gtk_widget_show (label7);
  gtk_container_add (GTK_CONTAINER (eventbox12), label7);
  gtk_widget_set_size_request (label7, 80, 25);

  eventbox13 = gtk_event_box_new ();
  gtk_widget_show (eventbox13);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox13, 40, 400);
  gtk_widget_set_size_request (eventbox13, 128, 32);

  label8 = gtk_label_new (_("Education"));
  gtk_widget_show (label8);
  gtk_container_add (GTK_CONTAINER (eventbox13), label8);
  gtk_widget_set_size_request (label8, 128, 32);

  eventbox14 = gtk_event_box_new ();
  gtk_widget_show (eventbox14);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox14, 216, 360);
  gtk_widget_set_size_request (eventbox14, 116, 24);

  radiobutton_homme_reclam = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (radiobutton_homme_reclam);
  gtk_container_add (GTK_CONTAINER (eventbox14), radiobutton_homme_reclam);
  gtk_widget_set_size_request (radiobutton_homme_reclam, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_homme_reclam), radiobutton_homme_reclam_group);
  radiobutton_homme_reclam_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_homme_reclam));

  eventbox15 = gtk_event_box_new ();
  gtk_widget_show (eventbox15);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox15, 400, 360);
  gtk_widget_set_size_request (eventbox15, 116, 24);

  radiobutton_femme_reclam = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (radiobutton_femme_reclam);
  gtk_container_add (GTK_CONTAINER (eventbox15), radiobutton_femme_reclam);
  gtk_widget_set_size_request (radiobutton_femme_reclam, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_femme_reclam), radiobutton_homme_reclam_group);
  radiobutton_homme_reclam_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_femme_reclam));

  eventbox16 = gtk_event_box_new ();
  gtk_widget_show (eventbox16);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox16, 208, 400);
  gtk_widget_set_size_request (eventbox16, 160, 24);

  checkbutton_prepa_reclam = gtk_check_button_new_with_mnemonic (_("Cycle pr\303\251paratoire"));
  gtk_widget_show (checkbutton_prepa_reclam);
  gtk_container_add (GTK_CONTAINER (eventbox16), checkbutton_prepa_reclam);
  gtk_widget_set_size_request (checkbutton_prepa_reclam, 160, 24);

  eventbox17 = gtk_event_box_new ();
  gtk_widget_show (eventbox17);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox17, 392, 400);
  gtk_widget_set_size_request (eventbox17, 160, 24);

  checkbutton_ing_reclam = gtk_check_button_new_with_mnemonic (_("Cycle d ing\303\251nieur"));
  gtk_widget_show (checkbutton_ing_reclam);
  gtk_container_add (GTK_CONTAINER (eventbox17), checkbutton_ing_reclam);
  gtk_widget_set_size_request (checkbutton_ing_reclam, 160, 24);

  eventbox18 = gtk_event_box_new ();
  gtk_widget_show (eventbox18);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox18, 584, 400);
  gtk_widget_set_size_request (eventbox18, 126, 24);

  checkbutton_business_reclam = gtk_check_button_new_with_mnemonic (_("Business"));
  gtk_widget_show (checkbutton_business_reclam);
  gtk_container_add (GTK_CONTAINER (eventbox18), checkbutton_business_reclam);
  gtk_widget_set_size_request (checkbutton_business_reclam, 126, 24);

  eventbox19 = gtk_event_box_new ();
  gtk_widget_show (eventbox19);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox19, 96, 488);
  gtk_widget_set_size_request (eventbox19, 160, 37);

  button_ajouter_reclam = gtk_button_new ();
  gtk_widget_show (button_ajouter_reclam);
  gtk_container_add (GTK_CONTAINER (eventbox19), button_ajouter_reclam);
  gtk_widget_set_size_request (button_ajouter_reclam, 160, 37);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button_ajouter_reclam), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox1), label13, FALSE, FALSE, 0);

  eventbox20 = gtk_event_box_new ();
  gtk_widget_show (eventbox20);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox20, 336, 488);
  gtk_widget_set_size_request (eventbox20, 160, 37);

  button_modifier_reclam = gtk_button_new ();
  gtk_widget_show (button_modifier_reclam);
  gtk_container_add (GTK_CONTAINER (eventbox20), button_modifier_reclam);
  gtk_widget_set_size_request (button_modifier_reclam, 160, 37);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button_modifier_reclam), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox2), label14, FALSE, FALSE, 0);

  eventbox22 = gtk_event_box_new ();
  gtk_widget_show (eventbox22);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox22, 576, 488);
  gtk_widget_set_size_request (eventbox22, 160, 37);

  button_afficher_reclam = gtk_button_new ();
  gtk_widget_show (button_afficher_reclam);
  gtk_container_add (GTK_CONTAINER (eventbox22), button_afficher_reclam);
  gtk_widget_set_size_request (button_afficher_reclam, 160, 37);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button_afficher_reclam), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-justify-fill", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox3), label15, FALSE, FALSE, 0);

  image10 = create_pixmap (window_gestion_reclam, "school-books-on-desk--education-concept-871454068-5b548900c9e77c005b04fc8c.jpg");
  gtk_widget_show (image10);
  gtk_fixed_put (GTK_FIXED (fixed1), image10, 0, -16);
  gtk_widget_set_size_request (image10, 1072, 744);

  g_signal_connect ((gpointer) radiobutton_homme_reclam, "toggled",
                    G_CALLBACK (on_radiobutton_homme_reclam_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_femme_reclam, "toggled",
                    G_CALLBACK (on_radiobutton_femme_reclam_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_prepa_reclam, "toggled",
                    G_CALLBACK (on_checkbutton_prepa_reclam_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_ing_reclam, "toggled",
                    G_CALLBACK (on_checkbutton_ing_reclam_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_business_reclam, "toggled",
                    G_CALLBACK (on_checkbutton_business_reclam_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_ajouter_reclam, "clicked",
                    G_CALLBACK (on_button_ajouter_reclam_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_modifier_reclam, "clicked",
                    G_CALLBACK (on_button_modifier_reclam_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_afficher_reclam, "clicked",
                    G_CALLBACK (on_button_afficher_reclam_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_gestion_reclam, window_gestion_reclam, "window_gestion_reclam");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, entry_id_reclam, "entry_id_reclam");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, entry_cin_reclam, "entry_cin_reclam");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, entry_nom_reclam, "entry_nom_reclam");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, entry_prenom_reclam, "entry_prenom_reclam");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, entryreclam, "entryreclam");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, spinbutton_jour_reclam, "spinbutton_jour_reclam");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, spinbutton_mois_reclam, "spinbutton_mois_reclam");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, spinbutton_annee_reclam, "spinbutton_annee_reclam");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, eventbox1, "eventbox1");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, label1, "label1");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, eventbox2, "eventbox2");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, label2, "label2");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, eventbox3, "eventbox3");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, label3, "label3");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, eventbox4, "eventbox4");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, label5, "label5");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, eventbox5, "eventbox5");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, label6, "label6");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, eventbox6, "eventbox6");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, combobox_reclam, "combobox_reclam");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, eventbox7, "eventbox7");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, label4, "label4");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, eventbox8, "eventbox8");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, label10, "label10");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, eventbox9, "eventbox9");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, label11, "label11");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, eventbox10, "eventbox10");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, label12, "label12");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, eventbox11, "eventbox11");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, label9, "label9");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, eventbox12, "eventbox12");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, label7, "label7");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, eventbox13, "eventbox13");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, label8, "label8");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, eventbox14, "eventbox14");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, radiobutton_homme_reclam, "radiobutton_homme_reclam");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, eventbox15, "eventbox15");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, radiobutton_femme_reclam, "radiobutton_femme_reclam");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, eventbox16, "eventbox16");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, checkbutton_prepa_reclam, "checkbutton_prepa_reclam");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, eventbox17, "eventbox17");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, checkbutton_ing_reclam, "checkbutton_ing_reclam");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, eventbox18, "eventbox18");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, checkbutton_business_reclam, "checkbutton_business_reclam");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, eventbox19, "eventbox19");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, button_ajouter_reclam, "button_ajouter_reclam");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, image1, "image1");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, label13, "label13");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, eventbox20, "eventbox20");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, button_modifier_reclam, "button_modifier_reclam");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, image2, "image2");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, label14, "label14");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, eventbox22, "eventbox22");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, button_afficher_reclam, "button_afficher_reclam");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, image3, "image3");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, label15, "label15");
  GLADE_HOOKUP_OBJECT (window_gestion_reclam, image10, "image10");

  return window_gestion_reclam;
}

GtkWidget*
create_window_afficher_reclam (void)
{
  GtkWidget *window_afficher_reclam;
  GtkWidget *fixed2;
  GtkWidget *entry_recherche_cin_reclam;
  GtkWidget *eventbox23;
  GtkWidget *label16;
  GtkWidget *eventbox24;
  GtkWidget *button_rechercher_reclam;
  GtkWidget *image4;
  GtkWidget *eventbox25;
  GtkWidget *button_go_to_ajouter_reclam;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image5;
  GtkWidget *label17;
  GtkWidget *eventbox26;
  GtkWidget *button_go_to_modifier_reclam;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image6;
  GtkWidget *label18;
  GtkWidget *eventbox27;
  GtkWidget *button_supprimer_reclam;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image7;
  GtkWidget *label19;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview1;
  GtkWidget *eventbox28;
  GtkWidget *button_dashboard_reclam;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image12;
  GtkWidget *label24;
  GtkWidget *image11;

  window_afficher_reclam = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_afficher_reclam), _("Espace Etudiant"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (window_afficher_reclam), fixed2);

  entry_recherche_cin_reclam = gtk_entry_new ();
  gtk_widget_show (entry_recherche_cin_reclam);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_recherche_cin_reclam, 360, 24);
  gtk_widget_set_size_request (entry_recherche_cin_reclam, 176, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_recherche_cin_reclam), 8226);

  eventbox23 = gtk_event_box_new ();
  gtk_widget_show (eventbox23);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox23, 264, 24);
  gtk_widget_set_size_request (eventbox23, 65, 24);

  label16 = gtk_label_new (_("CIN"));
  gtk_widget_show (label16);
  gtk_container_add (GTK_CONTAINER (eventbox23), label16);
  gtk_widget_set_size_request (label16, 65, 24);

  eventbox24 = gtk_event_box_new ();
  gtk_widget_show (eventbox24);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox24, 584, 24);
  gtk_widget_set_size_request (eventbox24, 66, 29);

  button_rechercher_reclam = gtk_button_new ();
  gtk_widget_show (button_rechercher_reclam);
  gtk_container_add (GTK_CONTAINER (eventbox24), button_rechercher_reclam);
  gtk_widget_set_size_request (button_rechercher_reclam, 66, 29);

  image4 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_container_add (GTK_CONTAINER (button_rechercher_reclam), image4);

  eventbox25 = gtk_event_box_new ();
  gtk_widget_show (eventbox25);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox25, 656, 224);
  gtk_widget_set_size_request (eventbox25, 226, 40);

  button_go_to_ajouter_reclam = gtk_button_new ();
  gtk_widget_show (button_go_to_ajouter_reclam);
  gtk_container_add (GTK_CONTAINER (eventbox25), button_go_to_ajouter_reclam);
  gtk_widget_set_size_request (button_go_to_ajouter_reclam, 226, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button_go_to_ajouter_reclam), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image5 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox4), image5, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("Ajouter une r\303\251clamation"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox4), label17, FALSE, FALSE, 0);

  eventbox26 = gtk_event_box_new ();
  gtk_widget_show (eventbox26);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox26, 656, 280);
  gtk_widget_set_size_request (eventbox26, 226, 40);

  button_go_to_modifier_reclam = gtk_button_new ();
  gtk_widget_show (button_go_to_modifier_reclam);
  gtk_container_add (GTK_CONTAINER (eventbox26), button_go_to_modifier_reclam);
  gtk_widget_set_size_request (button_go_to_modifier_reclam, 226, 40);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button_go_to_modifier_reclam), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image6 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox5), image6, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("Modifier une r\303\251clamation"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox5), label18, FALSE, FALSE, 0);

  eventbox27 = gtk_event_box_new ();
  gtk_widget_show (eventbox27);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox27, 656, 336);
  gtk_widget_set_size_request (eventbox27, 232, 40);

  button_supprimer_reclam = gtk_button_new ();
  gtk_widget_show (button_supprimer_reclam);
  gtk_container_add (GTK_CONTAINER (eventbox27), button_supprimer_reclam);
  gtk_widget_set_size_request (button_supprimer_reclam, 232, 40);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button_supprimer_reclam), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image7 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox6), image7, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("Supprimer une r\303\251clamation"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox6), label19, FALSE, FALSE, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed2), scrolledwindow1, 32, 168);
  gtk_widget_set_size_request (scrolledwindow1, 616, 368);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview1);
  gtk_widget_set_size_request (treeview1, 568, 288);

  eventbox28 = gtk_event_box_new ();
  gtk_widget_show (eventbox28);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox28, 656, 392);
  gtk_widget_set_size_request (eventbox28, 232, 40);

  button_dashboard_reclam = gtk_button_new ();
  gtk_widget_show (button_dashboard_reclam);
  gtk_container_add (GTK_CONTAINER (eventbox28), button_dashboard_reclam);
  gtk_widget_set_size_request (button_dashboard_reclam, 232, 40);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button_dashboard_reclam), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image12 = gtk_image_new_from_stock ("gtk-page-setup", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox7), image12, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("Dashboard"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox7), label24, FALSE, FALSE, 0);

  image11 = create_pixmap (window_afficher_reclam, "school-books-on-desk--education-concept-871454068-5b548900c9e77c005b04fc8c.jpg");
  gtk_widget_show (image11);
  gtk_fixed_put (GTK_FIXED (fixed2), image11, 0, 0);
  gtk_widget_set_size_request (image11, 1288, 712);

  g_signal_connect ((gpointer) button_rechercher_reclam, "clicked",
                    G_CALLBACK (on_button_rechercher_reclam_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_go_to_ajouter_reclam, "clicked",
                    G_CALLBACK (on_button_go_to_ajouter_reclam_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_go_to_modifier_reclam, "clicked",
                    G_CALLBACK (on_button_go_to_modifier_reclam_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_supprimer_reclam, "clicked",
                    G_CALLBACK (on_button_supprimer_reclam_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_dashboard_reclam, "clicked",
                    G_CALLBACK (on_button_dashboard_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_afficher_reclam, window_afficher_reclam, "window_afficher_reclam");
  GLADE_HOOKUP_OBJECT (window_afficher_reclam, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window_afficher_reclam, entry_recherche_cin_reclam, "entry_recherche_cin_reclam");
  GLADE_HOOKUP_OBJECT (window_afficher_reclam, eventbox23, "eventbox23");
  GLADE_HOOKUP_OBJECT (window_afficher_reclam, label16, "label16");
  GLADE_HOOKUP_OBJECT (window_afficher_reclam, eventbox24, "eventbox24");
  GLADE_HOOKUP_OBJECT (window_afficher_reclam, button_rechercher_reclam, "button_rechercher_reclam");
  GLADE_HOOKUP_OBJECT (window_afficher_reclam, image4, "image4");
  GLADE_HOOKUP_OBJECT (window_afficher_reclam, eventbox25, "eventbox25");
  GLADE_HOOKUP_OBJECT (window_afficher_reclam, button_go_to_ajouter_reclam, "button_go_to_ajouter_reclam");
  GLADE_HOOKUP_OBJECT (window_afficher_reclam, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window_afficher_reclam, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window_afficher_reclam, image5, "image5");
  GLADE_HOOKUP_OBJECT (window_afficher_reclam, label17, "label17");
  GLADE_HOOKUP_OBJECT (window_afficher_reclam, eventbox26, "eventbox26");
  GLADE_HOOKUP_OBJECT (window_afficher_reclam, button_go_to_modifier_reclam, "button_go_to_modifier_reclam");
  GLADE_HOOKUP_OBJECT (window_afficher_reclam, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window_afficher_reclam, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (window_afficher_reclam, image6, "image6");
  GLADE_HOOKUP_OBJECT (window_afficher_reclam, label18, "label18");
  GLADE_HOOKUP_OBJECT (window_afficher_reclam, eventbox27, "eventbox27");
  GLADE_HOOKUP_OBJECT (window_afficher_reclam, button_supprimer_reclam, "button_supprimer_reclam");
  GLADE_HOOKUP_OBJECT (window_afficher_reclam, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (window_afficher_reclam, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (window_afficher_reclam, image7, "image7");
  GLADE_HOOKUP_OBJECT (window_afficher_reclam, label19, "label19");
  GLADE_HOOKUP_OBJECT (window_afficher_reclam, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (window_afficher_reclam, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (window_afficher_reclam, eventbox28, "eventbox28");
  GLADE_HOOKUP_OBJECT (window_afficher_reclam, button_dashboard_reclam, "button_dashboard_reclam");
  GLADE_HOOKUP_OBJECT (window_afficher_reclam, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (window_afficher_reclam, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (window_afficher_reclam, image12, "image12");
  GLADE_HOOKUP_OBJECT (window_afficher_reclam, label24, "label24");
  GLADE_HOOKUP_OBJECT (window_afficher_reclam, image11, "image11");

  return window_afficher_reclam;
}

GtkWidget*
create_dialog_echec_ajout_reclam (void)
{
  GtkWidget *dialog_echec_ajout_reclam;
  GtkWidget *dialog_vbox1;
  GtkWidget *fixed3;
  GtkWidget *label20;
  GtkWidget *dialog_action_area1;
  GtkWidget *closebutton1;

  dialog_echec_ajout_reclam = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog_echec_ajout_reclam), _("v\303\251rification d ajout"));
  gtk_window_set_type_hint (GTK_WINDOW (dialog_echec_ajout_reclam), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog_echec_ajout_reclam), FALSE);

  dialog_vbox1 = GTK_DIALOG (dialog_echec_ajout_reclam)->vbox;
  gtk_widget_show (dialog_vbox1);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), fixed3, TRUE, TRUE, 0);

  label20 = gtk_label_new (_("ID existe d\303\251ja"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed3), label20, 64, 48);
  gtk_widget_set_size_request (label20, 144, 41);

  dialog_action_area1 = GTK_DIALOG (dialog_echec_ajout_reclam)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  closebutton1 = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (closebutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_echec_ajout_reclam), closebutton1, GTK_RESPONSE_CLOSE);
  GTK_WIDGET_SET_FLAGS (closebutton1, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) closebutton1, "clicked",
                    G_CALLBACK (on_closebutton1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_echec_ajout_reclam, dialog_echec_ajout_reclam, "dialog_echec_ajout_reclam");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_echec_ajout_reclam, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (dialog_echec_ajout_reclam, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (dialog_echec_ajout_reclam, label20, "label20");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_echec_ajout_reclam, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (dialog_echec_ajout_reclam, closebutton1, "closebutton1");

  return dialog_echec_ajout_reclam;
}

GtkWidget*
create_dialog_succes_ajout_reclam (void)
{
  GtkWidget *dialog_succes_ajout_reclam;
  GtkWidget *dialog_vbox2;
  GtkWidget *fixed4;
  GtkWidget *label21;
  GtkWidget *dialog_action_area2;
  GtkWidget *closebutton2;

  dialog_succes_ajout_reclam = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog_succes_ajout_reclam), _("Verification d ajout"));
  gtk_window_set_type_hint (GTK_WINDOW (dialog_succes_ajout_reclam), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog_succes_ajout_reclam), FALSE);

  dialog_vbox2 = GTK_DIALOG (dialog_succes_ajout_reclam)->vbox;
  gtk_widget_show (dialog_vbox2);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), fixed4, TRUE, TRUE, 0);

  label21 = gtk_label_new (_("Ajout avec succ\303\251s"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed4), label21, 104, 56);
  gtk_widget_set_size_request (label21, 152, 33);

  dialog_action_area2 = GTK_DIALOG (dialog_succes_ajout_reclam)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  closebutton2 = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (closebutton2);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_succes_ajout_reclam), closebutton2, GTK_RESPONSE_CLOSE);
  GTK_WIDGET_SET_FLAGS (closebutton2, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) closebutton2, "clicked",
                    G_CALLBACK (on_closebutton2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_succes_ajout_reclam, dialog_succes_ajout_reclam, "dialog_succes_ajout_reclam");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_succes_ajout_reclam, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT (dialog_succes_ajout_reclam, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (dialog_succes_ajout_reclam, label21, "label21");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_succes_ajout_reclam, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (dialog_succes_ajout_reclam, closebutton2, "closebutton2");

  return dialog_succes_ajout_reclam;
}

GtkWidget*
create_dialog_echec_modif_reclam (void)
{
  GtkWidget *dialog_echec_modif_reclam;
  GtkWidget *dialog_vbox3;
  GtkWidget *fixed5;
  GtkWidget *label22;
  GtkWidget *dialog_action_area3;
  GtkWidget *closebutton3;

  dialog_echec_modif_reclam = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog_echec_modif_reclam), _("V\303\251rification de modification"));
  gtk_window_set_type_hint (GTK_WINDOW (dialog_echec_modif_reclam), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog_echec_modif_reclam), FALSE);

  dialog_vbox3 = GTK_DIALOG (dialog_echec_modif_reclam)->vbox;
  gtk_widget_show (dialog_vbox3);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_box_pack_start (GTK_BOX (dialog_vbox3), fixed5, TRUE, TRUE, 0);

  label22 = gtk_label_new (_("R\303\251clamation \303\240 modifier n'existe pas"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed5), label22, 8, 64);
  gtk_widget_set_size_request (label22, 256, 33);

  dialog_action_area3 = GTK_DIALOG (dialog_echec_modif_reclam)->action_area;
  gtk_widget_show (dialog_action_area3);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area3), GTK_BUTTONBOX_END);

  closebutton3 = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (closebutton3);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_echec_modif_reclam), closebutton3, GTK_RESPONSE_CLOSE);
  GTK_WIDGET_SET_FLAGS (closebutton3, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) closebutton3, "clicked",
                    G_CALLBACK (on_closebutton3_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_echec_modif_reclam, dialog_echec_modif_reclam, "dialog_echec_modif_reclam");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_echec_modif_reclam, dialog_vbox3, "dialog_vbox3");
  GLADE_HOOKUP_OBJECT (dialog_echec_modif_reclam, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (dialog_echec_modif_reclam, label22, "label22");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_echec_modif_reclam, dialog_action_area3, "dialog_action_area3");
  GLADE_HOOKUP_OBJECT (dialog_echec_modif_reclam, closebutton3, "closebutton3");

  return dialog_echec_modif_reclam;
}

GtkWidget*
create_dialog_succes_modif_reclam (void)
{
  GtkWidget *dialog_succes_modif_reclam;
  GtkWidget *dialog_vbox4;
  GtkWidget *fixed6;
  GtkWidget *label23;
  GtkWidget *dialog_action_area4;
  GtkWidget *closebutton4;

  dialog_succes_modif_reclam = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog_succes_modif_reclam), _("v\303\251rification de modification"));
  gtk_window_set_type_hint (GTK_WINDOW (dialog_succes_modif_reclam), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog_succes_modif_reclam), FALSE);

  dialog_vbox4 = GTK_DIALOG (dialog_succes_modif_reclam)->vbox;
  gtk_widget_show (dialog_vbox4);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_box_pack_start (GTK_BOX (dialog_vbox4), fixed6, TRUE, TRUE, 0);

  label23 = gtk_label_new (_("modification avec succ\303\251s"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed6), label23, 40, 72);
  gtk_widget_set_size_request (label23, 185, 33);

  dialog_action_area4 = GTK_DIALOG (dialog_succes_modif_reclam)->action_area;
  gtk_widget_show (dialog_action_area4);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area4), GTK_BUTTONBOX_END);

  closebutton4 = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (closebutton4);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_succes_modif_reclam), closebutton4, GTK_RESPONSE_CLOSE);
  GTK_WIDGET_SET_FLAGS (closebutton4, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) closebutton4, "clicked",
                    G_CALLBACK (on_closebutton4_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_succes_modif_reclam, dialog_succes_modif_reclam, "dialog_succes_modif_reclam");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_succes_modif_reclam, dialog_vbox4, "dialog_vbox4");
  GLADE_HOOKUP_OBJECT (dialog_succes_modif_reclam, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (dialog_succes_modif_reclam, label23, "label23");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_succes_modif_reclam, dialog_action_area4, "dialog_action_area4");
  GLADE_HOOKUP_OBJECT (dialog_succes_modif_reclam, closebutton4, "closebutton4");

  return dialog_succes_modif_reclam;
}

GtkWidget*
create_window_dashboard_reclam (void)
{
  GtkWidget *window_dashboard_reclam;
  GtkWidget *fixed7;
  GtkWidget *eventbox31;
  GtkWidget *button_service_plus_reclame;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image13;
  GtkWidget *label26;
  GtkWidget *eventbox32;
  GtkWidget *label_service_plus_reclame;
  GtkWidget *eventbox33;
  GtkWidget *button_retour_reclam;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image14;
  GtkWidget *label27;
  GtkWidget *image15;

  window_dashboard_reclam = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_dashboard_reclam), _("Dashboard"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (window_dashboard_reclam), fixed7);

  eventbox31 = gtk_event_box_new ();
  gtk_widget_show (eventbox31);
  gtk_fixed_put (GTK_FIXED (fixed7), eventbox31, 232, 48);
  gtk_widget_set_size_request (eventbox31, 472, 48);

  button_service_plus_reclame = gtk_button_new ();
  gtk_widget_show (button_service_plus_reclame);
  gtk_container_add (GTK_CONTAINER (eventbox31), button_service_plus_reclame);
  gtk_widget_set_size_request (button_service_plus_reclame, 472, 48);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button_service_plus_reclame), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image13 = gtk_image_new_from_stock ("gtk-go-down", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox8), image13, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("Le service le plus reclam\303\251 est :"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox8), label26, FALSE, FALSE, 0);

  eventbox32 = gtk_event_box_new ();
  gtk_widget_show (eventbox32);
  gtk_fixed_put (GTK_FIXED (fixed7), eventbox32, 88, 200);
  gtk_widget_set_size_request (eventbox32, 792, 64);

  label_service_plus_reclame = gtk_label_new ("");
  gtk_widget_show (label_service_plus_reclame);
  gtk_container_add (GTK_CONTAINER (eventbox32), label_service_plus_reclame);
  gtk_widget_set_size_request (label_service_plus_reclame, 792, 64);

  eventbox33 = gtk_event_box_new ();
  gtk_widget_show (eventbox33);
  gtk_fixed_put (GTK_FIXED (fixed7), eventbox33, 400, 512);
  gtk_widget_set_size_request (eventbox33, 160, 37);

  button_retour_reclam = gtk_button_new ();
  gtk_widget_show (button_retour_reclam);
  gtk_container_add (GTK_CONTAINER (eventbox33), button_retour_reclam);
  gtk_widget_set_size_request (button_retour_reclam, 160, 37);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button_retour_reclam), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image14 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox9), image14, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox9), label27, FALSE, FALSE, 0);

  image15 = create_pixmap (window_dashboard_reclam, "school-books-on-desk--education-concept-871454068-5b548900c9e77c005b04fc8c.jpg");
  gtk_widget_show (image15);
  gtk_fixed_put (GTK_FIXED (fixed7), image15, 0, -32);
  gtk_widget_set_size_request (image15, 960, 744);

  g_signal_connect ((gpointer) button_service_plus_reclame, "clicked",
                    G_CALLBACK (on_button_service_plus_reclame_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_retour_reclam, "clicked",
                    G_CALLBACK (on_button_retour_reclam_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_dashboard_reclam, window_dashboard_reclam, "window_dashboard_reclam");
  GLADE_HOOKUP_OBJECT (window_dashboard_reclam, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (window_dashboard_reclam, eventbox31, "eventbox31");
  GLADE_HOOKUP_OBJECT (window_dashboard_reclam, button_service_plus_reclame, "button_service_plus_reclame");
  GLADE_HOOKUP_OBJECT (window_dashboard_reclam, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (window_dashboard_reclam, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (window_dashboard_reclam, image13, "image13");
  GLADE_HOOKUP_OBJECT (window_dashboard_reclam, label26, "label26");
  GLADE_HOOKUP_OBJECT (window_dashboard_reclam, eventbox32, "eventbox32");
  GLADE_HOOKUP_OBJECT (window_dashboard_reclam, label_service_plus_reclame, "label_service_plus_reclame");
  GLADE_HOOKUP_OBJECT (window_dashboard_reclam, eventbox33, "eventbox33");
  GLADE_HOOKUP_OBJECT (window_dashboard_reclam, button_retour_reclam, "button_retour_reclam");
  GLADE_HOOKUP_OBJECT (window_dashboard_reclam, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (window_dashboard_reclam, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (window_dashboard_reclam, image14, "image14");
  GLADE_HOOKUP_OBJECT (window_dashboard_reclam, label27, "label27");
  GLADE_HOOKUP_OBJECT (window_dashboard_reclam, image15, "image15");

  return window_dashboard_reclam;
}

