/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *window_gestion_reclam;
  GtkWidget *window_afficher_reclam;
  GtkWidget *dialog_echec_ajout_reclam;
  GtkWidget *dialog_succes_ajout_reclam;
  GtkWidget *dialog_echec_modif_reclam;
  GtkWidget *dialog_succes_modif_reclam;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
 
 
  window_afficher_reclam = create_window_afficher_reclam ();
  gtk_widget_show (window_afficher_reclam);
  
  gtk_main ();
  return 0;
}

